# =============================================================================
# TEMPLATE BASE BUILD
# =============================================================================

.base-build: &base-build
  allow_failure: true
  stage: reports
  variables:
    GIT_STRATEGY: fetch
  before_script:
    - |
      if ! docker info &>/dev/null; then
        if [ -z "${DOCKER_HOST}" -a "${KUBERNETES_PORT}" ]; then
          export DOCKER_HOST="tcp://localhost:2375"
        fi
      fi
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    when: on_success
    paths: [gl-code-quality-report.json, gl-code-quality-report.txt, gl-code-quality-report.html]
    expire_in: "15 day"
  only:
    refs:
      - merge_requests

# =============================================================================
# JOB CODE QUALITY
# =============================================================================

# APP

job:code-quality-app-merge-request:
  extends: .changes-app
  <<: *base-build
  script:
    - docker run --rm --env CODECLIMATE_CODE="${PWD}/app/code" --env CODECLIMATE_DEBUG="1" --env REPORT_STDOUT="1" --volume "${PWD}/app/code":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze -f json > gl-code-quality-report.json
    - docker run --rm --env CODECLIMATE_CODE="${PWD}/app/code" --env CODECLIMATE_DEBUG="1" --env REPORT_STDOUT="1" --volume "${PWD}/app/code":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze -f text > gl-code-quality-report.txt
    - docker run --rm --env CODECLIMATE_CODE="${PWD}/app/code" --env CODECLIMATE_DEBUG="1" --env REPORT_STDOUT="1" --volume "${PWD}/app/code":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze -f html > gl-code-quality-report.html
