# =============================================================================
# LOCAL VARIABLES
# =============================================================================

.base-variables: &base-variables
  PATH_DOCKERFILE: ${NS}/Dockerfile
  GIT_STRATEGY: fetch

# =============================================================================
# TEMPLATE BASE AUDIT
# =============================================================================

.base-build: &base-build
  image: alpine:3.10
  extends: .default-retry
  allow_failure: false
  stage: review
  before_script:
    - apk add --update --no-cache git bash
    - git clone --depth 1 https://github.com/CISOfy/lynis -b master
    - chmod a+x ./scripts/verify.sh && cd ./lynis
    - ./lynis audit dockerfile ../${PATH_DOCKERFILE} --verbose && cd ..

# =============================================================================
# JOB AUDIT
# =============================================================================

# APP
job:audit-app-develop:
  <<: *base-build
  variables:
    NS: app
    <<: *base-variables
  script:
    - ./scripts/verify.sh -f /var/log/lynis.log
  only:
    refs:
      - develop
    changes:
      - "app/Dockerfile"
