# =============================================================================
# LOCAL VARIABLES
# =============================================================================

.base-variables: &base-variables
  GIT_STRATEGY: none
  CI_APPLICATION_REPOSITORY: ${CI_REGISTRY_IMAGE}/${NS}
  CI_APPLICATION_TAG: ${CI_COMMIT_SHA}

# =============================================================================
# TEMPLATE BASE BUILD
# =============================================================================

.base-build: &base-build
  allow_failure: false
  stage: scanning
  before_script:
    - apk add --update --no-cache wget ca-certificates bash
    - wget https://github.com/arminc/clair-scanner/releases/download/v8/clair-scanner_linux_amd64 && touch clair-whitelist.yml
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - docker container run -d --name db arminc/clair-db:latest
    - docker container run -p 6060:6060 --link db:postgres -d --name clair --restart on-failure arminc/clair-local-scan:v2.0.1
    - mv ./clair-scanner_linux_amd64 ./clair-scanner
    - chmod +x ./clair-scanner
    - while( ! wget -q -O /dev/null http://$(hostname):6060/v1/namespaces ) ; do sleep 1 ; done
    - retries=0
    - echo -e "\nWaiting for clair daemon to start.\n"
    - while( ! wget -T 10 -q -O /dev/null http://$(hostname):6060/v1/namespaces ) ; do sleep 1 ; echo -n "." ; if [ ${retries} -eq 10 ] ; then echo " Timeout, aborting." ; exit 1 ; fi ; retries=$(($retries+1)) ; done
    - docker pull ${CI_APPLICATION_REPOSITORY}:${CI_APPLICATION_TAG}
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    paths: [gl-container-scanning-report.json]
    when: on_success
    expire_in: "15 day"
  only:
    refs:
      - develop

# =============================================================================
# JOB SCANNING
# =============================================================================

# APP
job:scanning-app-develop:
  <<: *base-build
  extends: .changes-app
  variables:
    NS: app
    <<: *base-variables
  script:
    - ./clair-scanner -c http://$(hostname):6060 --ip $(hostname -i) -r gl-container-scanning-report.json -l clair.log -w clair-whitelist.yml ${CI_APPLICATION_REPOSITORY}:${CI_APPLICATION_TAG} || true
