# =============================================================================
# LOCAL VARIABLES
# =============================================================================

.base-variables: &base-variables
  BRANCH: stage
  GIT_STRATEGY: fetch
  BUILD_IMAGE_TAG: ${CI_REGISTRY_IMAGE}/${NS}:${BRANCH}
  BUILD_IMAGE_TAG_HASH: ${CI_REGISTRY_IMAGE}/${NS}:${CI_COMMIT_SHA}
  BUILD_DOCKERFILE: ${NS}/Dockerfile
  BUILD_CONTEXT: ${NS}/

# =============================================================================
# TEMPLATE BASE BUILD
# =============================================================================

.base-build: &base-build
  allow_failure: false
  stage: build
  before_script:
    - apk add --update --no-cache bash && chmod a+x ./scripts/build.sh
  only:
    refs:
      - stage

# =============================================================================
# JOB BUILD
# =============================================================================

# BACKEND

job:build-backend-stage:
  <<: *base-build
  extends: .changes-backend
  variables:
    NS: backend
    <<: *base-variables
  script:
    - ./scripts/build.sh

# DATABASE

job:build-database-stage:
  <<: *base-build
  extends: .changes-database
  variables:
    NS: database
    <<: *base-variables
  script:
    - ./scripts/build.sh

# FLYWAY

job:build-flyway-stage:
  <<: *base-build
  extends: .changes-flyway
  variables:
    NS: flyway
    <<: *base-variables
  script:
    - ./scripts/build.sh

# FRONTEND

job:build-frontend-stage:
  <<: *base-build
  extends: .changes-frontend
  variables:
    NS: frontend
    <<: *base-variables
  script:
    - ./scripts/build.sh
