# =============================================================================
# LOCAL VARIABLES
# =============================================================================

.base-variables: &base-variables
  PATH_DOCKERFILE: ${NS}/Dockerfile
  GIT_STRATEGY: fetch

# =============================================================================
# TEMPLATE BASE AUDIT
# =============================================================================

.base-build: &base-build
  image: alpine:3.10
  extends: .default-retry
  allow_failure: false
  stage: review
  before_script:
    - apk add --update --no-cache git bash
    - git clone --depth 1 https://github.com/CISOfy/lynis -b master
    - chmod a+x ./scripts/verify.sh && cd ./lynis
    - ./lynis audit dockerfile ../${PATH_DOCKERFILE} --verbose && cd ..

# =============================================================================
# JOB AUDIT
# =============================================================================

# BACKEND

job:audit-backend-master:
  <<: *base-build
  variables:
    NS: backend
    <<: *base-variables
  script:
    - ./scripts/verify.sh -f /var/log/lynis.log
  only:
    refs:
      - master
    changes:
      - "backend/Dockerfile"

# DATABASE

job:audit-database-master:
  <<: *base-build
  variables:
    NS: database
    <<: *base-variables
  script:
    - ./scripts/verify.sh -f /var/log/lynis.log
  only:
    refs:
      - master
    changes:
      - "database/Dockerfile"

# FLYWAY

job:audit-flyway-master:
  <<: *base-build
  variables:
    NS: flyway
    <<: *base-variables
  script:
    - ./scripts/verify.sh -f /var/log/lynis.log
  only:
    refs:
      - master
    changes:
      - "flyway/Dockerfile"

# FRONTEND

job:audit-frontend-master:
  <<: *base-build
  variables:
    NS: frontend
    <<: *base-variables
  script:
    - ./scripts/verify.sh -f /var/log/lynis.log
  only:
    refs:
      - master
    changes:
      - "frontend/Dockerfile"
