# =============================================================================
# TEMPLATE DEFAULT TAGS
# =============================================================================

.default-tags: &default-tags
  tags:
    - kubernetes

# =============================================================================
# TEMPLATE DEFAULT RETRY
# =============================================================================

.default-retry: &default-retry
  <<: *default-tags
  retry:
    max: 2 # This is confusing but this means "3 runs at max".
    when:
      - unknown_failure
      - api_failure
      - runner_system_failure

# =============================================================================
# TEMPLATE CHANGES
# =============================================================================

# APP
.changes-app:
  <<: *default-retry
  only:
    changes:
      - "app/*"
      - "app/**/*"
      - "app/code/**/*"
      - "app/Dockerfile"
      - "app/CHANGELOG.md"
      - "CHANGELOG.md"

# MERGE
.changes-merge:
  <<: *default-retry
  only:
    changes:
      - "app/*"
      - "app/**/*"
      - "app/code/**/*"
      - "app/Dockerfile"
      - "app/CHANGELOG.md"
      - "CHANGELOG.md"

# LINT YML
.changes-lint-yml:
  <<: *default-retry
  only:
    changes:
      - "**/*.{yml, yaml}"
      - "*.{yml, yaml}"
    refs:
      - master
      - merge_requests

# LINT DOCS
.changes-lint-docs:
  <<: *default-retry
  only:
    changes:
      - "docs/*"
      - "CHANGELOG.md"
  except:
    - master
    - stage
